Add usage; improve opts

diff --git a/runParser b/runParser
--- a/runParser
+++ b/runParser
@@ -1,20 +1,32 @@
 #!/usr/bin/bash
 
-filter=''
-merge=''
-annotate=''
+filter=0
+merge=0
+annotate=0
 
 while getopts 'fma' flag; do
   case "${flag}" in
-    f) filter='true' ;;
-    m) merge='true' ;;
-    a) annotate='true' ;;
+    f) filter=1 ;;
+    m) merge=1 ;;
+    a) annotate=1 ;;
+    h) usage exit 0 ;;
     *) error "Unexpected option ${flag}" ;;
   esac
 done
 
+## usage
+usage() {
+    echo "
+usage:   run_parser.sh [options]
+options:
+  -f    filter
+  -m    merge
+  -a    annotate
+  -h    show this message
+"
+}
 
-if $filter = true
+if [[ $filter -eq 1 ]]
 then
   for delly_file in data/lumpy/*.vcf
   do
@@ -38,18 +50,24 @@ fi
 
 cd filtered
 
-if $merge = true
-then
-  pwd
+mergeVCF=`which mergevcf || true`
 
+if [[ -z "$mergeVCF" ]]
+then
+  usage
+  echo -e "Error: mergevcf was not found. Please set in path\n"
+  exit 1
+fi
+
+if [[ $merge -eq 1 ]]
+then
   echo "perl ../script/merge_vcf.pl"
   perl ../script/merge_vcf.pl
-
 fi
 
 cd summary
 
-if $merge = true
+if [[ $merge -eq 1 ]]
 then
   samples+=( $(ls -1 *.txt | cut -d '.' -f 1 | sort -u ) )
 
@@ -58,31 +76,33 @@ then
     echo "perl ../../script/svMerger.pl -f ${samples[i]}*.txt"
     perl ../../script/svMerger.pl -f ${samples[i]}*.txt
   done
+
 fi
 
 cd merged
 
 features=/Users/Nick/Documents/Curie/Data/Genomes/Dmel_v6.12/Features/dmel-all-r6.12.gtf
 
-if [ -f all_genes.txt ]
+if [[ $annotate -eq 1 ]]
 then
-  rm all_genes.txt
-fi
 
-if [ -f all_bps.txt ]
-then
-  rm all_bps.txt
-fi
+  if [ -f all_genes.txt ]
+  then
+    rm all_genes.txt
+  fi
 
-
-if $annotate = true
-then
+  if [ -f all_bps.txt ]
+  then
+    rm all_bps.txt
+  fi
 
   for merged_file in *merged_SVs.txt
   do
     echo "Annotating $merged_file"
-    echo "perl ../../../script/sv2gene.pl $features $merged_file"
-
-    perl ../../../script/sv2gene.pl $features $merged_file
+    echo "perl ../../../script/sv2gene.v0.1.pl $features $merged_file"
+    perl ../../../script/sv2gene.v0.1.pl $features $merged_file
   done
+
 fi
+
+exit 0
